POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "me",
  "url": "blog.com"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Nice blog",
  "author": "Harshal",
  "url": "fb.com",
  "likes": 0
}

###
GET http://localhost:3001/api/blogs
Accept: application/json

###
